# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 95%
        threshold: 1%
        base: auto
        if_ci_failed: error
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  branches:
    - main

flags:
  backend:
    paths:
      - src/
    carryforward: true
    after_n_builds: 1
  dashboard:
    paths:
      - dashboard/
    carryforward: true
    after_n_builds: 1

ignore:
  - "**/__pycache__/**"
  - "**/tests/**"
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/conftest.py"
  - "**/migrations/**"
  - "**/*.d.ts"
  - "**/node_modules/**"
  - "**/__tests__/**"
  - "**/coverage/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.next/**"
